name: Backend CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - '!**.md'
  pull_request:
    branches: [ "main" ]
    paths:
    - '!**.md'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3-prerelease
      with:
        arguments: build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run tests and generate JaCoCo coverage report
        run: ./gradlew test jacocoTestReport
      - name: Upload coverage report to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/
          
